import React,{useState} from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Link from "next/link";

const Layout = ({children}) => {
const [IsAuth, setIsAuth] = useState(false)
React.useEffect(() => {
    if (localStorage) {
const accessToken=localStorage.getItem("token")
        if(accessToken){
            setIsAuth(true)
          
        }else{
            setIsAuth(false)
         
        }
    }
  });

    return (
        <div >
            <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

       
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous"></link>
        </Head>
       {!IsAuth ?(<>
        <div className={styles.AuthLink} >
          <p >SignIn</p>
            <p >Register</p>
          </div>
       
       </>):(<></>)}
        
      
        
        <nav className={styles.nave}>
         
            
            <div className={styles.navButt}>
              
                  <h6 >
                    <Link href="/Home">
                         <a className="navbar-brand">Home</a>
                    </Link>
                    </h6>
                    
                 
                    <h6>
                    <Link href="/login">
                           <a className="navbar-brand">About</a>
                        </Link>
                        </h6><h6>
                        <Link href="/login">
                           <a className="navbar-brand">Contact Us</a>
                        </Link></h6>

                <div>
                 
             
                </div>
            </div>
       
        
        </nav>
           

            <main className={styles.main}>

            {children}
            </main>
            <footer className={styles.footer}>
                
                 <p>&copy; All right Reserved</p>
             </footer>
        </div>
    )
}
export default Layout
